### ISSUE TITLE
Crashes with the expansion

### ISSUE THREAD

**Issue by kelhor** [ahom/ffxiv_reverse#1]
Hi! I know you don't maintain this anymore, but I'm looking at getting it running with the expansion's dats. They've changed the index format (now two index files each), and was wondering if you had any insight before I go digging too deeply.

If not, or this really doesn't interest you anymore, that's okay. What you've given me so far has been a huge step forward. Thanks!

**Comment by ahom** [comment]
Hey!

To be honest I don't know yet what the other index file is for, I recently rewrote some of this as golang code (actually this was to practice go :p) and the only stopping point I had was that there were new texture formats, the first index file is working like before AFAICT and I don't know yet if the second one is really needed.

**The crash you are referring to, what did you run and what is the stack_trace/logs?**

Cheers.

**Comment by kelhor** [comment]
Hi! Thanks for responding.

So, I just have a simple client to call export_as_csvs:

```
int _tmain(int argc, _TCHAR* argv[])
{
    boost::log::add_file_log("extractor.log");

    boost::log::core::get()->set_filter(xiv::utils::log::severity_level >= xiv::utils::log::Severity::trace);

    auto game_data = xiv::dat::GameData("D:\\ffxiv-copy\\game\\sqpack\\ffxiv");
    xiv::exd::ExdData exddata(game_data);
    exddata.export_as_csvs("D:\\ffxiv-dump\\");
    return 0;
}
```

If I point that at an older set of XIV files (like 2.2), it works fine. On a current installation, it chokes around the end of its first category (Achievements) for the base game. It doesn't work on the expansion files at all, because the filename format has changed (the whole filename is significant now, now just the first two characters, and HW uses the extra chars). It doesn't give me a specific error or trace; just calls abort() and dies.

Anyway, I can keep digging, just knowing that I can ignore the index2 helps a ton.

**Comment by ahom** [comment]
Oh ok, yeah I know why it's crashing.
There are new types in the exd data aswell, pretty easy to spot and to understand which type they are though, I totally forgot I had to adapt this for the go version I'm doing :D

I guess either you are curious and want to look for it or I can give you the new types!
They are defined here: https://github.com/ahom/ffxiv_reverse/blob/master/xiv/exd/include/xiv/exd/Exh.h#L8

btw if you adapt the types in this file I wouldn't be against a pull request. :+1: 

Cheers.

**Comment by kelhor** [comment]
I won't deny my curiosity, but if I could have them, that'd be awesome. Trying to get something written that the dats are just the first step for. I'd be happy to submit a PR with anything I do that could be useful, though!

**Comment by ahom** [comment]
```
const (
    StringType  = 0
    BooleanType = 1
    Int8Type    = 2
    UInt8Type   = 3
    Int16Type   = 4
    UInt16Type  = 5
    Int32Type   = 6
    UInt32Type  = 7
    Float32Type = 9
    UInt64Type  = 11

    Bit1Type = 25
    Bit2Type = 26
    Bit3Type = 27
    Bit4Type = 28
    Bit5Type = 29
    Bit6Type = 30
    Bit7Type = 31
    Bit8Type = 32
)
```

New types are the bitfields, quite self explicit I guess, Bit1Type means that it is bit 1 of the byte etc...

**Comment by kelhor** [comment]
They have different types for specific bits in the byte? That's... interesting. Why would anyone even want to do that, instead of just using a byte, since you have to grab the whole byte anyway (smallest unit of addressable memory).

**Comment by ahom** [comment]
That's miles and miles away of the worst things I've seen in those dats ;D lol

And just to clarify, they usually just reference the same byte but with multiple fields with these bittypes.

**Comment by kelhor** [comment]
Having spent enough time with their XI code, that doesn't surprise me in the least.

Thanks again for all your help, time to beat my head against this for a while as I try to remember C++ :D

**Comment by ahom** [comment]
Np!

If ever you need some help with your pet project don't hesitate to ask, I'm not that busy these days :p

**Comment by kelhor** [comment]
Ha, greatly appreciated. My pet project is a actually a new XIV data miner for FFXIAH. We've been using a dumped sqlite DB from the phone app, but it stopped getting updated, so I needed a new method.

I was originally just going to scrape the Lodestone, but the IDs don't match, and it was enough of a pain in the ass that I decided to just go after the dats themselves, which led me here :)

**Comment by ahom** [comment]
As a FYI, I just checked quickly tonight what the `.index2` was about and it's definitely not **really** usefull in the case of getting files out.

Basically it stores the same list of files the `.index` does, the only difference is that the list is indexed by the hash of the `full_path` of the file, whereas in `.index` it is indexed by the hash of the `directory_path` and the hash of the `filename`.

I'm guessing it might be usefull if there are some hash collisions in index, but still have to check if there are actually collisions :p

**Comment by kelhor** [comment]
Yeah, I noticed that they were all basically half the size, assumed there was some kind of correlation. Interesting that it's basically a redundancy.

**Comment by kelhor** [comment]
It's working now! Thanks so much for all of your help; I'll have some PRs ready for you in a little while if you're interested :)

**Comment by ahom** [comment]
Happy to hear it! And I would gladly accept PRs!

Cheers.
